### PR TITLE
Delete tmp directory when bump manifesto invalid

### PR DESCRIPTION
**Pull request by pawbu**
- added checking for tmp directory when application starts up

### CODE REVIEW

**Comment by essbb** [comment]
Looks good to me :)

**Comment by DanielElisenberg** [comment]
@essbb we should make this usage consistent in a refactor I agree

**Review by DanielElisenberg — APPROVED** [review]
Looks great :100: good typehint and docstring updates too 🌶

**Comment by pawbu** [comment]
> Looks good to me :)
> 
> Minor nit: I see that we are mixing os.path and pathlib functions (not that it matters)

Yes, this mix-up is across the whole project. We need to refactor this at a later stage.

**Pull request merged**
