### PR TITLE
Delete left-over csv files after these have been processed

### PR DESCRIPTION
**Pull request by essbb**
Not sure if we should delete additional files, please advise!

### CODE REVIEW

**Review by vaskalan — COMMENTED** [review]
Looks good to me. What about a unit test verifying the files are actually deleted?

**Comment by essbb** [comment]
> Looks good to me. What about a unit test verifying the files are actually deleted?

Good point. I did verify it by inspecting the resulting output though. Will look into it but I think we may need some refactoring of the app to support proper testing.

**Comment by DanielElisenberg** [comment]
There are actually more files that are generated by a build_dataset_worker that needs cleaning up.
When importing a dataset 'INNTEKT', I printed the contents of the working_directory after one run:
```
INNTEKT.db
INNTEKT.json
INNTEKT.csv
INNTEKT_pseudonymized.csv
INNTEKT_pseudonymized_enriched.csv
INNTEKT__DRAFT.json
INNTEKT__DRAFT.parquet
```

The two __DRAFT files we want to keep, as these are getting imported into the datastore, but the top 5 files are generated in the same way based on the dataset name and are not used for anything after the worker is done 👍🏻 

Writing a unit test based on this should probably lead in the right direction 👍🏻

**Comment by essbb** [comment]
I thought we were supposed to keep the *.db ?

**Comment by DanielElisenberg** [comment]
> I thought we were supposed to keep the *.db ?

The db file is generated for efficient validation. (Sorting the data to look for duplicates etc.) So it can be deleted after the work ^^

**Comment by essbb** [comment]
@DanielElisenberg could you point out where the db file is created. For some reason it eludes me...

**Comment by DanielElisenberg** [comment]
@essbb It eludes you for good reason 😅 The db files are generated by the microdata-validator in order to validate quickly. So it is generated through the use of the microdata-validator dependency. Give me a call if I should clarify more 📞

**Review by DanielElisenberg — APPROVED** [review]
:100: Looks good

**Pull request merged**
